version: '3.7'
services:
  app:
    container_name: nest-app
    build: .
    tty: true
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - my-redis
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./src/config/env/.production.env
    logging:
      driver: json-file
      options:
        max-size: 8m
        max-file: '5'
  my-redis:
    container_name: ${REDIS_HOST}
    image: 'redis:7.0.12-alpine'
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - ./redis/data:/data
    restart: always
    env_file:
      - ./src/config/env/.production.env
    logging:
      driver: json-file
      options:
        max-size: 8m
        max-file: '5'
